#!/bin/bash

	# -----------------------------------------------------------------------
	# helpers
u_calci() {
	# integer arithmetic ($1)
	ret="$(echo "$1" | bc)"
	echo "$ret"
}

u_calcf() {
	# floating point arithmetic ($1)
	ret="$(echo "$1" | bc -l)"
	echo "$ret"
}

u_width() {
	# text width ($1)
	ret="$(u_calcf "$(xftwidth "$FONT_NAME:size=$FONT_SIZE" "$1")+2")"
	echo "$ret"
}

u_height() {
	# text height ($1)
	ret="$(xftheight "$FONT_NAME:size=$FONT_SIZE" "$1")"
	echo "$ret"
}

u_listi() {
	# n-th ($2) line of text ($1)
	ret="$(awk -v n="$2" 'NR==n' <<< "$1")"
	echo "$ret"
}

